// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi1Ri8fkEfF6nMvLL-nfZP7SwwcFn5bho',
    appId: '1:1061342250574:web:0f842adc98ef3e65d5651f',
    messagingSenderId: '1061342250574',
    projectId: 'project-management-891e3',
    authDomain: 'project-management-891e3.firebaseapp.com',
    storageBucket: 'project-management-891e3.appspot.com',
    measurementId: 'G-47JDXS2P6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuUoXdLqxI7LdwOhluVZH0JqwRaMKLAeY',
    appId: '1:1061342250574:android:3a57e5769aa8d0bbd5651f',
    messagingSenderId: '1061342250574',
    projectId: 'project-management-891e3',
    storageBucket: 'project-management-891e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD929Oe9vGsOh-_rO78EeMpNHY8d_xyWk',
    appId: '1:1061342250574:ios:0bf92db7f314c588d5651f',
    messagingSenderId: '1061342250574',
    projectId: 'project-management-891e3',
    storageBucket: 'project-management-891e3.appspot.com',
    iosBundleId: 'com.example.projectManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD929Oe9vGsOh-_rO78EeMpNHY8d_xyWk',
    appId: '1:1061342250574:ios:a277264328072de1d5651f',
    messagingSenderId: '1061342250574',
    projectId: 'project-management-891e3',
    storageBucket: 'project-management-891e3.appspot.com',
    iosBundleId: 'com.example.projectManagement.RunnerTests',
  );
}
